version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: 5100
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRESS_PASSWORD: postgres
      POSTGRESS_PORT: 5432
#    ports:
#      - 5100:5100
#      - 9229:9229
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    image: postgis/postgis
#    ports:
#      - '${POSTGRESS_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./nest-postgres-db:/var/lib/postgresql/nest-postgres
    restart: on-failure
  web:
    image: nginx:alpine
    ports:
    - "80:80"
    restart: on-failure
    volumes:
    - ./frontend:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  nest-postgres-db:
